spring:
  application:
    name: image_tag_service
  profiles:
    group:
      local: local
      prod: prod
  cloud:
    gcp:
      project_id: ${GOOGLE_PROJECT_ID}
      credentials: ${GOOGLE_APPLICATION_CREDENTIALS}

  # MultiPartFile 사이즈
  servlet:
    multipart:
      max-file-size: 10MB

  data:
    redis:
      port: ${SPRING_REDIS_PORT}
      host: ${SPRING_REDIS_HOST}
---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod

auth:
  server-url: ${AUTH_SERVER_URL}
  api-url: ${AUTH_API_URL}