spring:
  application:
    name: image_tag_service

  cloud:
    gcp:
      project_id: ${GOOGLE_PROJECT_ID}
      credentials: ${GOOGLE_APPLICATION_CREDENTIALS}

  # MultiPartFile 사이즈
  servlet:
    multipart:
      max-file-size: 10MB

auth:
  server-url: ${AUTH_SERVER_URL}
  api-url: ${AUTH_API_URL}